name: "Build Solution"
description: "Increments version and builds solution with MSBuild"

inputs:
  branch-postfix:
    description: "Postfix to add to version number for non-main branches"
    required: false
    default: ""
  version-prefix:
    description: "Prefix to add to version number for builds"
    required: true
    default: ""
  build-configuration:
    description: "Configuration to build the solution in"
    required: false
    default: "Release"
  project-name:
    description: "Name of the project/solution to build"
    required: true
  repo-token:
    description: "GitHub token for version increment"
    required: true

outputs:
  version:
    description: "The full version number used in the build"
    value: ${{inputs.version-prefix}}.${{ steps.version-increment.outputs.value }}${{ inputs.branch-postfix }}

runs:
  using: composite
  steps:
    - name: Increment Version
      id: version-increment
      uses: action-pack/increment@v2
      with:
        name: "VERSION"
        token: ${{ inputs.repo-token }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      shell: pwsh
      run: msbuild ${{ inputs.project-name }}.sln -t:rebuild -restore -property:Configuration=${{ inputs.build-configuration }} -property:Version=${{inputs.version-prefix}}.${{ steps.version-increment.outputs.value }}${{ inputs.branch-postfix }}
