name: "Discord Notification"
description: "Send a Discord notification about build status"

inputs:
  webhook-url:
    description: "Discord webhook URL"
    required: true
  version:
    description: "Build version number"
    required: true
  status:
    description: "Result of build"
    required: true

runs:
  using: composite
  steps:
    - name : Add SHORT_SHA Environment Variable
      id   : short-sha
      shell: bash
      run  : echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

    - name: Send Discord Notification
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ inputs.webhook-url }}
        embed-color: ${{ inputs.status == 'success' && '6284127' || '16538684' }}
        embed-description: "Build [${{ inputs.version }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) ([${{ env.SHORT_SHA }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})) of ${{ github.repository }}@${{ github.ref_name }} by **${{ github.actor }}** ${{ inputs.status == 'success' && 'completed' || 'failed' }}"
